INFO     HTTP_LOGGER:event_hooks.py:26 Make POST request to  http://localhost:8000/api/v1/users
INFO     HTTP_LOGGER:event_hooks.py:34 GOT 200 response to  OK from http://localhost:8000/api/v1/users
INFO     HTTP_LOGGER:event_hooks.py:26 Make POST request to  http://localhost:8000/api/v1/authentication/login
INFO     HTTP_LOGGER:event_hooks.py:34 GOT 200 response to  OK from http://localhost:8000/api/v1/authentication/login
INFO     HTTP_LOGGER:event_hooks.py:26 Make GET request to  http://localhost:8000/api/v1/files/incorrect-file-id
INFO     HTTP_LOGGER:event_hooks.py:34 GOT 422 response to  Unprocessable Content from http://localhost:8000/api/v1/files/incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:10 Check that response status code equal 422
INFO     FILE_ASSERTIONS:files.py:102 Check get file with incorrect file id response
INFO     ERRORS_ASSERTIONS:errors.py:19 Check validation error response
INFO     BASE_ASSERTIONS:base.py:44 Check that 'details' length equals to [ValidationErrorSchema(type='uuid_parsing', input='incorrect-file-id', context={'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}, message='Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1', location=['path', 'file_id'])]
INFO     ERRORS_ASSERTIONS:errors.py:10 Check validation error
INFO     BASE_ASSERTIONS:base.py:19 Check that 'type' equals to uuid_parsing
INFO     BASE_ASSERTIONS:base.py:19 Check that 'input' equals to incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:19 Check that 'context' equals to {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}
INFO     BASE_ASSERTIONS:base.py:19 Check that 'message' equals to Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1
INFO     BASE_ASSERTIONS:base.py:19 Check that 'location' equals to ['path', 'file_id']
INFO     SCHEMA_ASSERTIONS:schema.py:19 Validating json schema